#file: noinspection SpringBootApplicationYaml
server:
  port: 8087
  tomcat:
    threads:
      max: 200        # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
      min-spare: 50   # 初始化线程数,最小空闲线程数,默认是10
    accept-count: 10  # 等待队列长度
  servlet:
    context-path: /api/${app.config.api-version}

# 应用配置 app.config.api-version
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin:  '*'

#  -Djasypt.encryptor.password=lijiaqiang1024@wt1314520
#java -Djasypt.encryptor.password=lijiaqiang1024@wt1314520 -jar course-push-app.jar
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    property:
      prefix: ENC(
      suffix: )

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

csdn:
  cookies: 'uuid_tt_dd=10_20290684990-1753209489095-887032; fid=20_31381811281-1753209442061-606290; UN=m0_62310006; p_uid=U010000; csdn_newcert_m0_62310006=1; c_dl_prid=-; c_dl_rid=1754235235033_293829; c_dl_fref=https://blog.csdn.net/csdnerM/article/details/136784455; c_dl_fpage=/download/weixin_38682054/12751987; c_dl_um=distribute.pc_relevant.none-task-blog-2%7Edefault%7EOPENSEARCH%7EPaidSort-1-142236198-blog-136784455.235%5Ev43%5Epc_blog_bottom_relevance_base5; creative_btn_mp=3; c_segment=8; dc_sid=0123faae676a263a99fd648f62228e53; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=1755949540,1755963493,1755963576,1756006743; HMACCOUNT=90350D62738A95D6; _clck=139wy3g%5E2%5Efyq%5E0%5E2059; c_ab_test=1; yd_captcha_token=MTc1NjAxNjA5ODgxNF8xMjAuMjI2LjI4LjU2X2YyMzNkZDY0Yzg0MDBmOWM3NTUzNTAzOTI4ZTVkMDU4OTkwMA%3D%3D; https_ydclearance=cc06fe9378550d2ee709e5a9-ff3b-403e-baa2-3f509a9e0f35-1756033128; dc_session_id=10_1756025928685.364480; bc_bot_fp=01453adf2f9a8f4d8967afa95855acc6; FCNEC=%5B%5B%22AKsRol8kz72tthqqBmeou4-1OwOeVEUFb7kvqGEHY3_ayAowasTknFy-6Pf6q15sxkTYPvPA99lbCWmJqtbxtlre7FCn0PWX1SHcoGSgSiiX1jyP2mMGHuKmahojC7u8hScAXymnHoQOkHTVhwu7WnpAKihqEeyABw%3D%3D%22%5D%5D; c_first_ref=default; c_first_page=https%3A//blog.csdn.net/m0_62310006/article/details/150701174; c_dsid=11_1756031859368.059056; creativeSetApiNew=%7B%22toolbarImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20230921102607.png%22%2C%22publishSuccessImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20240229024608.png%22%2C%22articleNum%22%3A9%2C%22type%22%3A2%2C%22oldUser%22%3Atrue%2C%22useSeven%22%3Afalse%2C%22oldFullVersion%22%3Atrue%2C%22userName%22%3A%22m0_62310006%22%7D; __gads=ID=fee264c5b112516f:T=1755783435:RT=1756032329:S=ALNI_MY7VIXDAAEa_M8ToJQ7WXOZEBgMeA; __gpi=UID=00001183e64c7543:T=1755783435:RT=1756032329:S=ALNI_MaqzQZCxvVLa85akPGMR4wsa4L2Rg; __eoi=ID=87f6282774d5a9b7:T=1755783435:RT=1756032329:S=AA-AfjbK8v_Jip84jQmol_qV0IDw; SESSION=f5c18dcb-bdfe-4f2a-b21c-602e12142e3e; c_pref=https%3A//blog.csdn.net/m0_62310006/article/details/150701174%3Fspm%3D1001.2014.3001.5501; c_ref=https%3A//blog.csdn.net/m0_62310006%3Ftype%3Dblog; hide_login=1; loginbox_strategy=%7B%22taskId%22%3A317%2C%22abCheckTime%22%3A1756032360551%2C%22version%22%3A%22ExpA%22%2C%22nickName%22%3A%22%E6%B5%81%E5%B9%B4%E6%9F%93%E6%8C%87%E6%82%B2%E4%BC%A4%E3%80%81%22%7D; UserName=m0_62310006; UserInfo=fb433bf2573b41dbb51461c5f062f20d; UserToken=fb433bf2573b41dbb51461c5f062f20d; UserNick=%E6%B5%81%E5%B9%B4%E6%9F%93%E6%8C%87%E6%82%B2%E4%BC%A4%E3%80%81; AU=1E9; BT=1756032376912; c_page_id=default; log_Id_pv=20; bc_bot_session=1756032378b42c3fe45fc2f2bd; waf_captcha_marker=956a30c77efaca4506bec9528ad2733db87ffbd28413ecd5531d0a4169add6da; Hm_lpvt_6bcd52f51e9b3dce32bec4a3997715ac=1756032378; https_waf_cookie=3e5770f1-728c-4bd039177a5907b9661cda7459905df6276e; log_Id_view=650; _clsk=oyagxf%5E1756032379410%5E4%5E0%5Ei.clarity.ms%2Fcollect;'
  categories: 'Java面试宝典'

spring:
  main:
    web-application-type: none
  # ollama ai
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/config/win-mcp-server-config.json
    openai:
      base-url: https://apis.itedus.cn/  # chat-gpt
      api-key: sk-eQ9OYl82ujfFPe682a26F4D0B8534c1281D32d1e724f6aBa  # chat-gpt
      chat:
        options:
          model: gpt-4.1-mini
      vector-table-name: vector_store_openai
      embedding:
        options:
          num-batch: 1536
          model: text-embedding-ada-002
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen3:14B
      embedding-model: nomic-embed-text
      vector-table-name: vector_store_ollama_deepseek
      # 向量模型
      embedding:
        options:
          # 配置模型处理的批量大小，这里设置为512。表示模型一次可以处理 512 个文本片段的嵌入请求
          num-batch: 768
    zhipuai:
      vector-table-name: vector_store_zhipuai
      image:
        base-url: https://open.bigmodel.cn/api/paas
        api-key: c3e3912426c49a7b990280b1d2d235a3.tcgJOlShzn6ba6uk
        options:
          model: GLM-4V-Flash
      chat:
        api-key: c3e3912426c49a7b990280b1d2d235a3.tcgJOlShzn6ba6uk
        base-url: https://open.bigmodel.cn/api/paas
        options:
          model: GLM-4-Flash-250414
          temperature: 0.7  # 设置温度参数
      embedding:
        options:
          dimensions: 1024
          model: embedding-3

  # 向量数据库
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ENC(kT6cWGip6fSnLJz5WVhGyaFeuFLsCQ6P)
    password: ENC(ny4D4WfjIPT9HhmlnXF5/7mY6JLchT+L)
    url: jdbc:postgresql://127.0.0.1:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1


jq1024:
  cc:
    # redisson 配置
    redisson:
      host: 127.0.0.1
      port: ENC(IoLWVdM0/gTgs+XZ+Gq8nA==)
      password: ENC(Xo8agmA26A3MM5iD1uGiwM1BOzNIN9zI)
      database: 0
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml